/// Spinner verbs displayed during processing.
///
/// Categorised into two groups:
/// 1. Cat-related — actions cats literally do
/// 2. Possibly cat-related — could pass as a cat behaviour with a creative eye
pub const SPINNER_VERBS: &[&str] = &[
    // ── Cat-related ───────────────────────────────────────────────
    "Basking",
    "Batting",
    "Chasing",
    "Clawing",
    "Crouching",
    "Darting",
    "Fidgeting",
    "Gliding",
    "Grooming",
    "Growling",
    "Hissing",
    "Hunting",
    "Kneading",
    "Leaping",
    "Licking",
    "Loafing",
    "Mauling",
    "Meowing",
    "Napping",
    "Pawing",
    "Playing",
    "Preening",
    "Prowling",
    "Purring",
    "Scratching",
    "Slinking",
    "Sleeping",
    "Sniffing",
    "Snuggling",
    "Stalking",
    "Stretching",
    "Swatting",
    "Yowling",
    // ── Possibly cat-related ──────────────────────────────────────
    "Beboppin'",
    "Booping",
    "Burrowing",
    "Dilly-dallying",
    "Doodling",
    "Ebbing",
    "Flambéing",
    "Fluttering",
    "Frolicking",
    "Galloping",
    "Grooving",
    "Herding",
    "Honking",
    "Ionizing",
    "Lollygagging",
    "Meandering",
    "Misting",
    "Moonwalking",
    "Moseying",
    "Nesting",
    "Noodling",
    "Orbiting",
    "Pouncing",
    "Puttering",
    "Ruminating",
    "Scampering",
    "Scurrying",
    "Shimmying",
    "Skedaddling",
    "Slithering",
    "Smooshing",
    "Spinning",
    "Swirling",
    "Swooping",
    "Twisting",
    "Undulating",
    "Unfurling",
    "Waddling",
    "Wandering",
    "Whisking",
    "Wibbling",
    "Zigzagging",
];

/// Past-tense verbs shown in the status row after a turn completes.
///
/// A mix of the neutral originals and a big pile of cat wordplay,
/// so "Purred for 2m 5s" and friends pad by when a turn finishes.
pub const TURN_COMPLETION_VERBS: &[&str] = &[
    // Neutral.
    "Baked",
    "Brewed",
    "Churned",
    "Cogitated",
    "Cooked",
    "Crunched",
    "Fermented",
    "Pondered",
    "Processed",
    "Worked",
    // Cat wordplay. 🐱
    "Purred",
    "Meowed",
    "Hissed",
    "Growled",
    "Scratched",
    "Clawed",
    "Licked",
    "Groomed",
    "Napped",
    "Slept",
    "Stretched",
    "Played",
    "Chased",
    "Pounced",
    "Hunted",
    "Mauled",
    "Swatted",
    "Batted",
    "Yowled",
    "Scampered",
    "Leapt",
    "Slinked",
    "Sniffed",
    "Prowled",
    "Stalked",
    "Kneaded",
    "Pawed",
    "Preened",
    "Snuggled",
    "Basked",
    "Loafed",
];

/// Select a random spinner verb.
pub fn sample_spinner_verb(seed: usize) -> &'static str {
    SPINNER_VERBS[seed % SPINNER_VERBS.len()]
}

/// Select a random completion verb.
pub fn sample_completion_verb(seed: usize) -> &'static str {
    TURN_COMPLETION_VERBS[seed % TURN_COMPLETION_VERBS.len()]
}
