// continuation.rs — In-loop continuation policy for `run_query_loop`.
//
// At the end of every turn that finishes with `end_turn` (no tool calls),
// `run_query_loop` consults a `ContinuationPolicy` to decide whether to keep
// going — and if so, with what follow-up user message — instead of always
// returning after one turn.
//
// This mirrors pi's agent-loop callbacks (`shouldStopAfterTurn`,
// `getFollowUpMessages`, `prepareNextTurn`) and its `agentLoopContinue`
// primitive for "keep going without a new user message". The decision now
// lives INSIDE the loop, so autonomous continuation (e.g. `/goal`) no longer
// requires the CLI REPL to re-dispatch a fresh turn after the loop returns.
//
// The default policy is `StopPolicy`: stop after one turn, exactly reproducing
// the historical non-goal behaviour. Goal-driven continuation is provided by
// `GoalPolicy` (see the goal-policy section below), which reuses the existing
// `goal_loop` guards (runaway cap, soft token budget, continuation message).

/// Inputs available to a continuation policy after a turn completes with
/// `end_turn` (no tool calls were requested).
pub struct TurnEndContext<'a> {
    /// Session identifier — used to look up any active goal for this session.
    pub session_id: &'a str,
    /// Cumulative token count for the whole session (soft-budget accounting).
    pub total_tokens_used: u64,
    /// Wall-clock seconds this turn took (goal time accounting).
    pub turn_elapsed_secs: u64,
    /// Working directory of the run — the project root verification commands
    /// are detected against and executed in.
    pub working_dir: &'a std::path::Path,
    /// Whether the turn's tool round included a file-writing tool. Used by the
    /// verify policy to skip verification for pure read/search turns.
    pub turn_made_writes: bool,
}

/// Decision returned by a continuation policy at the end of a completed turn.
#[derive(Debug, Clone)]
pub enum ContinuationDecision {
    /// Inject `message` as the next user turn and keep the loop running.
    Continue { message: String },
    /// Stop the loop. `note`, when present, is surfaced to the user as a
    /// status line (e.g. the goal's paused / budget-limited message).
    Stop { note: Option<String> },
}

impl ContinuationDecision {
    /// Whether this decision keeps the loop running.
    pub fn is_continue(&self) -> bool {
        matches!(self, ContinuationDecision::Continue { .. })
    }
}

/// A policy the runner consults at the end of each completed `end_turn` turn.
///
/// Implementations must be cheap and side-effect-aware: `decide` is called at
/// most once per turn, from the async loop, but must never hold a lock across
/// an `.await` (it is fully synchronous by design).
pub trait ContinuationPolicy: Send + Sync {
    fn decide(&self, ctx: &TurnEndContext<'_>) -> ContinuationDecision;

    /// Structured report of the most recent verification round, when this
    /// policy is the execute-and-verify policy and a round actually ran.
    /// Default: `None` — only `VerifyPolicy` overrides this. The query loop
    /// forwards the report as `QueryEvent::Verify` so the TUI can render the
    /// boxed per-check indicator.
    fn verify_report(&self) -> Option<crate::verify::VerifyReport> {
        None
    }

    /// Whether the end-of-turn checks will actually spawn. Default: `false`
    /// — only the execute-and-verify policy overrides this. The query loop
    /// calls it BEFORE the potentially slow checks run so the TUI can show a
    /// `verifying…` indicator instead of a silent wait.
    fn will_run_checks(&self, _ctx: &TurnEndContext<'_>) -> bool {
        false
    }

    /// Path to a spec generated by the turn that just ended, when this
    /// policy stopped the loop specifically so the spec can be reviewed.
    /// Default: `None` — only the spec-mode policy overrides this. The query
    /// loop forwards the path as `QueryEvent::SpecForReview` so the TUI can
    /// auto-open the Accept/Edit/Reject dialog for the generated spec (§10.2).
    fn spec_for_review(&self) -> Option<std::path::PathBuf> {
        None
    }
}

/// Default policy: always stop after the turn completes.
///
/// This is the historical, non-goal behaviour — a normal turn that ends with
/// `end_turn` returns immediately instead of continuing.
#[derive(Debug, Clone, Copy, Default)]
pub struct StopPolicy;

impl ContinuationPolicy for StopPolicy {
    fn decide(&self, _ctx: &TurnEndContext<'_>) -> ContinuationDecision {
        ContinuationDecision::Stop { note: None }
    }
}

/// Goal-driven continuation policy (the `/goal` feature).
///
/// Reuses the existing `goal_loop` guards verbatim — the runaway turn cap, the
/// soft token budget, and the per-turn continuation message. While the session
/// has an active goal and its guards allow, the loop continues with the goal
/// continuation message injected as the next user turn; otherwise it stops and
/// surfaces the same paused / budget-limited / runaway note as before.
///
/// This policy relocates only WHERE the decision is made (in-loop, per turn),
/// not the guards themselves: it delegates to
/// [`crate::goal_loop::check_and_continue_goal`], which opens the default goal
/// store and applies the identical logic the CLI post-loop path used to run.
#[derive(Debug, Clone, Copy, Default)]
pub struct GoalPolicy;

impl ContinuationPolicy for GoalPolicy {
    fn decide(&self, ctx: &TurnEndContext<'_>) -> ContinuationDecision {
        use crate::goal_loop::GoalContinuation;
        match crate::goal_loop::check_and_continue_goal(
            ctx.session_id,
            ctx.total_tokens_used,
            ctx.turn_elapsed_secs,
        ) {
            GoalContinuation::Continue { message } => ContinuationDecision::Continue { message },
            // Paused / budget / runaway / complete: stop, surfacing the same
            // user-facing note the CLI used to print.
            GoalContinuation::Stop { reason } => ContinuationDecision::Stop {
                note: reason.user_message(),
            },
            // No goal set for this session: behave exactly like `StopPolicy`.
            GoalContinuation::NoGoal => ContinuationDecision::Stop { note: None },
        }
    }
}

/// Spec-driven development continuation policy (audit spec Phase 4, §10).
///
/// After a turn that wrote files, checks whether a structured spec was
/// produced (`specs/<title>.json` in the working dir). If one exists, the
/// loop stops and surfaces the spec for the user to review (Accept / Edit /
/// Reject — the TUI review dialog or `/spec-review <file>`); the agent must
/// not implement against an unreviewed spec (§10.2). The chosen spec's path
/// is stashed so the query loop can auto-open the review dialog via
/// [`ContinuationPolicy::spec_for_review`]; the stash is cleared at the
/// start of every `decide`, so it only ever holds the current turn's spec.
/// If the turn produced no spec, behaves like `StopPolicy`.
#[derive(Debug, Default)]
pub struct SpecModePolicy {
    last_spec_path: std::sync::Mutex<Option<std::path::PathBuf>>,
}

impl SpecModePolicy {
    pub fn new() -> Self {
        Self::default()
    }
}

impl ContinuationPolicy for SpecModePolicy {
    fn decide(&self, ctx: &TurnEndContext<'_>) -> ContinuationDecision {
        // Reset first so `spec_for_review` never returns a stale path from a
        // previous turn once this decision completes.
        *self.last_spec_path.lock().unwrap() = None;
        if ctx.turn_made_writes {
            if let Some((path, spec)) = clawde_core::spec::Spec::latest_in(ctx.working_dir) {
                *self.last_spec_path.lock().unwrap() = Some(path.clone());
                return ContinuationDecision::Stop {
                    note: Some(format!(
                        "Spec generated: \"{}\" ({}). Review it before implementing — \
                         run /spec-review {}",
                        spec.title,
                        path.display(),
                        path.display()
                    )),
                };
            }
        }
        ContinuationDecision::Stop { note: None }
    }

    fn spec_for_review(&self) -> Option<std::path::PathBuf> {
        self.last_spec_path.lock().unwrap().clone()
    }
}

/// Selects which continuation policy `run_query_loop` uses for a run.
///
/// Stored on `QueryConfig` so callers opt in per invocation. Subagents,
/// headless runs, and every non-goal interactive turn use `Default`.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub enum ContinuationMode {
    /// Stop after the turn completes (default, non-goal behaviour).
    #[default]
    Default,
    /// Goal-driven autonomous continuation (the `/goal` feature).
    Goal,
    /// Execute-and-verify continuation (audit spec Phase 1): after a turn
    /// that wrote files, run the project's tests/lints and feed failures back
    /// to the model for auto-fix, up to `max_retries`.
    Verify(clawde_core::config::VerifyConfig),
    /// Spec-driven development (audit spec Phase 4, §10): after a turn that
    /// produced a spec, stop so the user can review it before implementation.
    SpecMode,
}

impl ContinuationMode {
    /// Build the concrete policy for this mode.
    ///
    /// `working_dir` is the project root verification commands are detected
    /// against and executed in (only used by the verify policy).
    pub fn policy(self, working_dir: &std::path::Path) -> Box<dyn ContinuationPolicy> {
        match self {
            ContinuationMode::Default => Box::new(StopPolicy),
            ContinuationMode::Goal => Box::new(GoalPolicy),
            ContinuationMode::Verify(config) => Box::new(crate::verify::VerifyPolicy::new(
                config,
                working_dir.to_path_buf(),
            )),
            ContinuationMode::SpecMode => Box::new(SpecModePolicy::new()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ctx() -> TurnEndContext<'static> {
        TurnEndContext {
            session_id: "sess",
            total_tokens_used: 0,
            turn_elapsed_secs: 0,
            working_dir: std::path::Path::new("."),
            turn_made_writes: true,
        }
    }

    #[test]
    fn stop_policy_always_stops() {
        let decision = StopPolicy.decide(&ctx());
        assert!(!decision.is_continue());
        match decision {
            ContinuationDecision::Stop { note } => assert!(note.is_none()),
            _ => panic!("StopPolicy must stop with no note"),
        }
    }

    #[test]
    fn default_mode_resolves_to_stop() {
        let policy = ContinuationMode::default().policy(std::path::Path::new("."));
        assert!(!policy.decide(&ctx()).is_continue());
    }
    #[test]
    fn verify_mode_resolves_to_verify_policy() {
        let cfg = clawde_core::config::VerifyConfig {
            enabled: false,
            ..Default::default()
        };
        let policy = ContinuationMode::Verify(cfg).policy(std::path::Path::new("."));
        // A disabled verify config stops silently, even on a writing turn.
        let decision = policy.decide(&ctx());
        assert!(!decision.is_continue());
        match decision {
            ContinuationDecision::Stop { note } => assert!(note.is_none()),
            _ => unreachable!(),
        }
    }

    #[test]
    fn spec_mode_stops_with_review_note_when_spec_written() {
        let dir = std::env::temp_dir().join(format!("clawde-spec-mode-{}", std::process::id()));
        std::fs::create_dir_all(dir.join("specs")).expect("create specs dir");
        let spec = clawde_core::spec::Spec {
            title: "Rate-Limiting Middleware".to_string(),
            ..Default::default()
        };
        spec.write_to(&dir.join("specs/rate-limiting.json"))
            .expect("write spec");

        let policy = SpecModePolicy::new();
        let decision = policy.decide(&TurnEndContext {
            session_id: "sess",
            total_tokens_used: 0,
            turn_elapsed_secs: 0,
            working_dir: &dir,
            turn_made_writes: true,
        });
        assert!(!decision.is_continue());
        match decision {
            ContinuationDecision::Stop { note } => {
                let note = note.expect("review note present");
                assert!(note.contains("Spec generated"));
                assert!(note.contains("Rate-Limiting Middleware"));
                assert!(note.contains("/spec-review"));
            }
            _ => unreachable!(),
        }
        // The generated spec's path is surfaced for auto-open.
        let review_path = policy
            .spec_for_review()
            .expect("spec path stashed for review");
        assert!(review_path.ends_with("rate-limiting.json"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn spec_for_review_clears_after_non_spec_turn() {
        let dir = std::env::temp_dir().join(format!("clawde-spec-mode-clr-{}", std::process::id()));
        std::fs::create_dir_all(dir.join("specs")).expect("create specs dir");
        let policy = SpecModePolicy::new();
        let spec = clawde_core::spec::Spec {
            title: "Rate-Limiting Middleware".to_string(),
            ..Default::default()
        };
        spec.write_to(&dir.join("specs/rate-limiting.json"))
            .expect("write spec");

        // First turn produces the spec → path stashed.
        policy.decide(&TurnEndContext {
            session_id: "sess",
            total_tokens_used: 0,
            turn_elapsed_secs: 0,
            working_dir: &dir,
            turn_made_writes: true,
        });
        assert!(policy.spec_for_review().is_some());
        // A later non-spec turn must not keep reporting the old path.
        policy.decide(&TurnEndContext {
            session_id: "sess",
            total_tokens_used: 0,
            turn_elapsed_secs: 0,
            working_dir: &dir,
            turn_made_writes: false,
        });
        assert!(policy.spec_for_review().is_none());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn spec_mode_stops_silently_without_spec() {
        let dir =
            std::env::temp_dir().join(format!("clawde-spec-mode-none-{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("create dir");
        let policy = SpecModePolicy::new();
        let decision = policy.decide(&TurnEndContext {
            session_id: "sess",
            total_tokens_used: 0,
            turn_elapsed_secs: 0,
            working_dir: &dir,
            turn_made_writes: true,
        });
        assert!(!decision.is_continue());
        match decision {
            ContinuationDecision::Stop { note } => assert!(note.is_none()),
            _ => unreachable!(),
        }
        // No spec was produced, so nothing is surfaced for review.
        assert!(policy.spec_for_review().is_none());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
